services:
  timeout-server:
    build: .
    command: ["./timeout-server", "--port=:8080", "--min-timeout=5s", "--max-timeout=12s"]
    restart: unless-stopped
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.timeout.entrypoints=websecure"
      - "traefik.http.routers.timeout.rule=PathPrefix(`timeout`)"
      - "traefik.http.services.timeout.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.timeout-strip.stripprefix.prefixes=timeout"
      - "traefik.http.routers.timeout.middlewares=timeout-strip"
      - "traefik.http.routers.snappy.tls.certresolver=tlsResolver"

networks:
  proxy:
    external: true